# Julia Basic Programming

References: 
* [Julia Documentation](https://docs.julialang.org/en/v1/)
* [Julia Tutorial](https://julialang.org/learning/)
* [Introduction to Julia(for programmers)](https://juliaacademy.com/courses/enrolled/375479)

## 1. What is Julia?

## 2. Why using Julia?

## 3. Basic Language Usages

### 3.1 Check documentation

Use `?` or `@doc` to check documentation of a function.

```julia
?println
@doc println
```

* Warning: `?` is not working in Jupyter Notebook.

    ```
    syntax: invalid identifier name "?"

    Stacktrace:
     [1] top-level scope
        @ ~/code/mml-book-julia/notebooks/00_IntroJulia.ipynb:2
    ```

Also, If the latex is not rendered correctly, please change the presentation style in VSCode.

| Step 1 | Step 2 |
|:-:|:-:|
| <img src='./figs/00-errorshow.png' width=100%> | <img src='./figs/00-errorshow2.png' width=100%> |

In [1]:
# check documentation
@doc sum

```
sum(f, itr; [init])
```

Sum the results of calling function `f` on each element of `itr`.

The return type is `Int` for signed integers of less than system word size, and `UInt` for unsigned integers of less than system word size.  For all other arguments, a common return type is found to which all arguments are promoted.

The value returned for empty `itr` can be specified by `init`. It must be the additive identity (i.e. zero) as it is unspecified whether `init` is used for non-empty collections.

!!! compat "Julia 1.6"
    Keyword argument `init` requires Julia 1.6 or later.


# Examples

```jldoctest
julia> sum(abs2, [2; 3; 4])
29
```

Note the important difference between `sum(A)` and `reduce(+, A)` for arrays with small integer eltype:

```jldoctest
julia> sum(Int8[100, 28])
128

julia> reduce(+, Int8[100, 28])
-128
```

In the former case, the integers are widened to system word size and therefore the result is 128. In the latter case, no such widening happens and integer overflow results in -128.

```
sum(itr; [init])
```

Return the sum of all elements in a collection.

The return type is `Int` for signed integers of less than system word size, and `UInt` for unsigned integers of less than system word size.  For all other arguments, a common return type is found to which all arguments are promoted.

The value returned for empty `itr` can be specified by `init`. It must be the additive identity (i.e. zero) as it is unspecified whether `init` is used for non-empty collections.

!!! compat "Julia 1.6"
    Keyword argument `init` requires Julia 1.6 or later.


See also: [`reduce`](@ref), [`mapreduce`](@ref), [`count`](@ref), [`union`](@ref).

# Examples

```jldoctest
julia> sum(1:20)
210

julia> sum(1:20; init = 0.0)
210.0
```

```
sum(A::AbstractArray; dims)
```

Sum elements of an array over the given dimensions.

# Examples

```jldoctest
julia> A = [1 2; 3 4]
2×2 Matrix{Int64}:
 1  2
 3  4

julia> sum(A, dims=1)
1×2 Matrix{Int64}:
 4  6

julia> sum(A, dims=2)
2×1 Matrix{Int64}:
 3
 7
```

```
sum(f, A::AbstractArray; dims)
```

Sum the results of calling function `f` on each element of an array over the given dimensions.

# Examples

```jldoctest
julia> A = [1 2; 3 4]
2×2 Matrix{Int64}:
 1  2
 3  4

julia> sum(abs2, A, dims=1)
1×2 Matrix{Int64}:
 10  20

julia> sum(abs2, A, dims=2)
2×1 Matrix{Int64}:
  5
 25
```


### 3.2 Variables, Printing and Comments

Use `println` to print a string.

In [2]:
println("Hello World!")

Hello World!


You can use `print` to print without a new line.

In [3]:
print("Hello ")
print("World!")

Hello World!

Similar to Python, Julia is a dynamically typed language. The type of a variable is determined by the value it holds.

In [4]:
x = 7
println(x)
println(typeof(x))

7


Int64


Use `#` to comment a line.

In [5]:
# julia code

### 3.3 Basic Math

In [6]:
# add
println(1 + 2)
# subtract
println(1 - 2)
# multiply
println(1 * 2)
# divide
println(1 / 2)
# power
println(2 ^ 3)
# remainder(modulus)
println(7 % 3)

3
-1
2


0.5
8
1


### 3.4 Data Types and Structures

```julia
- numbers: Int, Float64, Complex{Float64}
- string: String
```


### 3.4.1 String

Use double quotes `"` or `"""` to define a string.

In [7]:
# can add strings with `*` unlike python `+`
println("Hello" * " " * """World!""")
# `string` function can also be used for string interpolation
s1 = "Hello"
s2 = """World!"""
println(string(s1, " ", s2))
# like f-print in python, can use `$`
println("$s1 $s2")

Hello World!
Hello World!
Hello World!


### 3.4.2 Dictionaies

Dicionaries are similar to Python `dict`, but not ordered. You can define a dictionary by using `Dict()`.

In [8]:
word2index = Dict("Hello" => 1, "World!" => 2)
# Accessing elements with a key
println(word2index["Hello"])
# Adding a new key-value pair
word2index["Adam"] = 3
println(word2index)
# Removing a key-value pair with `pop!`
pop!(word2index, "Adam")
println(word2index)

1


Dict("World!" => 2, "Hello" => 1, "Adam" => 3)
Dict("World!" => 2, "Hello" => 1)


### 3.4.3 Tuples

Tuples are similar to Python `tuple`, cannot be changed. You can define a tuple by using `()`, `tuple()`. Be aware that `Tuple` is a type.

In [9]:
counting_stars = (1, 2, 3)
println("counting_stars = ", counting_stars)
counting_stars = tuple(1, 2, 3)
println("type is", typeof(counting_stars))
# indexing
println("first element of counting_stars = ", counting_stars[1])
# slicing: unlike python julia is 1-indexed
println("first two elements in counting_stars = ",counting_stars[1:2])
# try to modifiy tuple
println(counting_stars[1] = 2)

counting_stars = (1, 2, 3)
type is

Tuple{Int64, Int64, Int64}
first element of counting_stars = 1
first two elements in counting_stars = (1, 2)


ErrorException: syntax: invalid keyword argument name "counting_stars[1]" around /home/simonjisu/code/mml-book-julia/notebooks/00_IntroJulia.ipynb:10

### 3.4.4 Arrays

Arrays are similar to Python `list`, but can be changed.

In [10]:
numbers = [1, 2, 3]
println("numbers = ", numbers)
println("type is", typeof(numbers))
# add element, at the end
push!(numbers, 4)
println("push!: numbers = ", numbers)
# remove element
pop!(numbers)
println("pop!: numbers = ", numbers)
# indexing
println("first element of numbers = ", numbers[1])
# slicing
println("first two elements in numbers = ", numbers[1:2])

numbers = [1, 2, 3]
type isVector{Int64

}
push!: numbers = [1, 2, 3, 4]
pop!: numbers = [1, 2, 3]
first element of numbers = 1
first two elements in numbers = [1, 2]


In [25]:
# mixed type of elements
mixed = [1, "Hello", 2.5]
println("mixed type of array, mixed = ", mixed)
# once defined, cannot change type of elements
push!(numbers, "Hello")

mixed type of array, mixed = Any[1, "Hello", 2.5]


MethodError: MethodError: Cannot `convert` an object of type String to an object of type Int64

Closest candidates are:
  convert(::Type{T}, !Matched::T) where T<:Number
   @ Base number.jl:6
  convert(::Type{T}, !Matched::Number) where T<:Number
   @ Base number.jl:7
  convert(::Type{T}, !Matched::Base.TwicePrecision) where T<:Number
   @ Base twiceprecision.jl:273
  ...


### 3.4.5 Sets


In [32]:
s1 = Set([1, 2, 3, 3, 2, 1])
s2 = Set([2, 3, 4])
println("set 1 = ", s1)
println("set 2 = ", s2)
# two operation are different with `union` and `union!`, the latter modifies the set.
println("union of set 1 and set 2 = ", union(s1, s2))
println("After `union`:\n", " - Set 1 = ", s1, "\n - Set 2 = ", s2,)
println("union of set 1 and set 2 = ", union!(s1, s2))
println("After `union!`:\n", " - Set 1 = ", s1, "\n - Set 2 = ", s2,)
s1 = Set([1, 2, 3, 3, 2, 1])
s2 = Set([2, 3, 4])
# intersection
println("intersection of set 1 and set 2 = ", intersect(s1, s2))
# difference
println("difference of set 1 and set 2 = ", setdiff(s1, s2))

set 1 = Set([2, 3, 1])
set 2 = Set([4, 2, 3])
union of set 1 and set 2 = Set([4, 2, 3, 1])
After `union`:
 - Set 1 = Set([2, 3, 1])
 - Set 2 = Set([4, 2, 3])
union of set 1 and set 2 = Set([4, 2, 3, 1])
After `union!`:
 - Set 1 = Set([4, 2, 3, 1])
 - Set 2 = Set([4, 2, 3])
intersection of set 1 and set 2 = Set([2, 3])
difference of set 1 and set 2 = Set([1])
symmetric difference of set 1 and set 2 = Set([4, 1])


### 3.5 Control Flow